name: CI
 
on:
  push:
  workflow_dispatch:
 
env:
  CI: true
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  SKIP_ENV_VALIDATION: true
  E2E: true
 
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
 
      - name: Install PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 10.2.0
 
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
 
      - name: Install dependencies
        run: pnpm install
 
      - name: Push Database
        run: pnpm --filter @repo/db db:push
 
      - name: Build
        run: pnpm turbo build
 
      - name: Unit Tests - Utils
        run: pnpm test
        working-directory: packages/utils
 
      - name: Unit Tests - UI
        run: pnpm test
        working-directory: packages/ui
 
      - name: Unit Tests - Web
        run: pnpm test
        working-directory: apps/web
 
      - name: Install Playwright Browsers
        run: pnpm playwright install chromium --with-deps
        working-directory: tests/playwright
 
      - name: Seed Database
        run: curl http://localhost:3001/api/seed || true
 
      - name: E2E Tests
        run: pnpm turbo test-1 test-2 test-3