name: CI Pipeline
"on":
  - push
  - workflow_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    env:
      E2E: true
      CI: true
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      COURSE_ID: full-stack-development-comp3036-2026
      PASSWORD: ${{ secrets.PASSWORD }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      SKIP_ENV_VALIDATION: true
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 10.2.0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Install Playwright Browsers
        run: pnpm exec playwright install chromium --with-deps
      - name: Push Database
        run: pnpm --filter @repo/db db:push
      - name: Build
        run: pnpm turbo build

      - name: Unit Tests - Utils
        id: testUtils
        uses: WesternSydneyUniversity/autograding-command-grader@v2
        continue-on-error: true
        with:
          working-directory: packages/utils
          test-name: Unit 1 - Utils
          command: pnpm test
          timeout: 10
          max-score: 1

      - name: Unit Tests - UI
        id: testUi
        uses: WesternSydneyUniversity/autograding-command-grader@v2
        continue-on-error: true
        with:
          working-directory: packages/ui
          test-name: Unit 2 - UI
          command: pnpm test
          timeout: 10
          max-score: 1

      - name: Unit Tests - Web
        id: testWeb
        uses: WesternSydneyUniversity/autograding-command-grader@v2
        continue-on-error: true
        with:
          working-directory: apps/web
          test-name: Unit 3 - Web Components
          command: pnpm test
          timeout: 10
          max-score: 1

      - name: E2E Tests - Client
        id: npm1
        uses: WesternSydneyUniversity/autograding-command-grader@v2
        continue-on-error: true
        with:
          working-directory: .
          test-name: Part 1 - Client
          command: pnpm turbo test-1 --force
          timeout: 10
          max-score: 1

      - name: E2E Tests - Admin
        id: npm2
        uses: WesternSydneyUniversity/autograding-command-grader@v2
        continue-on-error: true
        with:
          working-directory: .
          test-name: Part 2 - Admin
          command: pnpm turbo test-2 --force
          timeout: 10
          max-score: 1

      - name: E2E Tests - Backend
        id: npm3
        uses: WesternSydneyUniversity/autograding-command-grader@v2
        continue-on-error: true
        with:
          working-directory: .
          test-name: Part 3 - Backend
          command: pnpm turbo test-3 --force
          timeout: 10
          max-score: 1

      - name: Autograding Reporter
        uses: education/autograding-grading-reporter@v1
        env:
          NPM1_RESULTS: "${{steps.npm1.outputs.result}}"
          NPM2_RESULTS: "${{steps.npm2.outputs.result}}"
          NPM3_RESULTS: "${{steps.npm3.outputs.result}}"
          TESTUTILS_RESULTS: "${{steps.testUtils.outputs.result}}"
          TESTUI_RESULTS: "${{steps.testUi.outputs.result}}"
          TESTWEB_RESULTS: "${{steps.testWeb.outputs.result}}"
        with:
          runners: npm1,npm2,npm3,testUtils,testUi,testWeb